### ISSUE TITLE
Fix documentation metadata

### ISSUE THREAD

**Issue by DariuszDepta** [CosmWasm/cw-multi-test#203]
Add to Cargo.toml:
```toml
[package.metadata.docs.rs]
all-features = true
```
to generate online documentation with all features set.
